apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekart-deployment
spec:
  replicas: 3 # Redundancy
  selector:
    matchLabels:
      app: ekart
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: ekart
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - ekart
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: ekart
          image: adijaiswal/ekart:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8070
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8070
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8070
            initialDelaySeconds: 10
            periodSeconds: 15

---

apiVersion: v1
kind: Service
metadata:
  name: ekart-ssvc
spec:
  selector:
    app: ekart
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070
  type: NodePort # NodePort to expose the service on localhost
  nodePort: 30007 # Optional: explicitly set NodePort, default range is 30000-32767

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ekart-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ekart-deployment
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
